ktlint:
  ClassSignature:
    active: false
  ImportOrdering:
    active: false
  TrailingCommaOnCallSite:
    active: true
    useTrailingCommaOnCallSite: false
  TrailingCommaOnDeclarationSite:
    active: true
    useTrailingCommaOnDeclarationSite: false

naming:
  InvalidPackageDeclaration:
    active: false

ORT:
  OrtImportOrder:
    active: true
  OrtPackageNaming:
    active: false
