name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotest.assertions.multi-line-diff=unified

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
    - name: Build all classes
      run: ./gradlew classes
  codeql-analysis:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      # Needed for SARIF scanning upload.
      security-events: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Initialize CodeQL
      uses: github/codeql-action/init@e0647621c2984b5ed2f768cb892365bf2a616ad1 # v4.37.2
      with:
        languages: java
        tools: nightly
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
    - name: Build all classes
      run: ./gradlew -Dorg.gradle.jvmargs=-Xmx1g classes
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@e0647621c2984b5ed2f768cb892365bf2a616ad1 # v4.37.2
  test:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
    - name: Run tests
      run: ./gradlew --scan test funTest
    - name: Create Test Summary
      uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2
      with:
        paths: "**/test-results/**/TEST-*.xml"
      if: always()
